"use client"
// import { useAuth } from '@/hooks/auth'
import '../css/globals.css'
// import "../css/globals.css";
// import type { Metadata } from "next";
import { Header, Bar } from '@/UI'
// export const metadata = {
//     title: 'Next.js',
//     description: 'Generated by Next.js',
// }
import { useAuth } from '@/hooks/auth'

export default function RootLayout({ children }) {
    //  const { user } = useAuth({ middleware: 'auth' })
    const { user } = useAuth({ middleware: 'guest' })
    return (
        <html lang="en">
            <body>
                {!user && <p>У вас нет прав доступа</p>}
                { user && user.is_active === 1 &&
                <>
                <Header />
                <Bar />
                {children}
                 </>
                }

            </body>
        </html>
    )
}
