// import { useAuth } from '@/hooks/auth'
import "../css/globals.css";
// import "../css/globals.css";
// import type { Metadata } from "next";
import { Header, Bar } from "@/UI"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    //  const { user } = useAuth({ middleware: 'auth' })

 return (
    <html lang="en">


      <body>
        <Header />
        <Bar />
        {children}
        </body>
    </html>
  )
}
